### ISSUE TITLE
Hey, is dit niet een nav?

### ISSUE THREAD

**Issue by KrijnHoetmer** [KaanKalmi/the-client-website-CROSSMARX#2]
Kijk eens naar https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

https://github.com/KaanKalmi/the-client-website-CROSSMARX/blob/31d621f69f7b5b6d44eed6d2ef710e8ffe307a57/index.html#L13-L25

**Comment by KaanKalmi** [comment]
Ohja dat moest k nog veranderen naar nav helemaal vergeten, k fix t nu!
