### ISSUE TITLE
Heading levels

### ISSUE THREAD

**Issue by KrijnHoetmer** [KaanKalmi/the-client-website-CROSSMARX#3]
Je gebruikt drie keer een h1; zijn die allemaal even belangrijk? Zijn dat dan niet h2's, en heb je dan niet nog een h1 daarboven nodig? Als ik puur naar je site kijk, mis ik ook nog een soort titel.. “Waar kijk ik naar?”

https://github.com/KaanKalmi/the-client-website-CROSSMARX/blob/31d621f69f7b5b6d44eed6d2ef710e8ffe307a57/index.html#L29C19-L29C19

**Comment by KaanKalmi** [comment]
fixed
