### ISSUE TITLE
Sectioning content

### ISSUE THREAD

**Issue by KrijnHoetmer** [KaanKalmi/the-client-website-CROSSMARX#4]
Hier lijkt een heading te ontbreken. Heb je dan wel een section nodig? Of kan dit ook een div zijn? Lees ook het artikel uit de slides even door: https://css-tricks.com/how-to-section-your-html/

https://github.com/KaanKalmi/the-client-website-CROSSMARX/blob/31d621f69f7b5b6d44eed6d2ef710e8ffe307a57/index.html#L26-L27

**Comment by KaanKalmi** [comment]
Deze is als het goed is nu ook gefixt
